# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tyh/Documents/pipeline/pipeline.cache/wt [current_project]
set_property parent.project_path /home/tyh/Documents/pipeline/pipeline.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /home/tyh/Downloads/ArchLab2015/ram_init_gen/loader.coe
add_files /home/tyh/Downloads/ArchLab2015/ram_init_gen/font.coe
add_files /home/tyh/Downloads/ArchLab2015/font.coe
add_files {{/home/tyh/Desktop/project /project.srcs/sources_1/imports/lab5/test/ArchLab2015/ram_init_gen/loader.coe}}
add_files -quiet /home/tyh/Documents/pipeline/pipeline.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp
set_property used_in_implementation false [get_files /home/tyh/Documents/pipeline/pipeline.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp]
add_files -quiet /home/tyh/Documents/pipeline/pipeline.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp
set_property used_in_implementation false [get_files /home/tyh/Documents/pipeline/pipeline.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp]
add_files -quiet {{/home/tyh/Desktop/project /project.srcs/font_mem/ip/font_mem/font_mem.dcp}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/font_mem/ip/font_mem/font_mem.dcp}}]
add_files -quiet {{/home/tyh/Desktop/project /project.srcs/loader_mem/ip/loader_mem/loader_mem.dcp}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/loader_mem/ip/loader_mem/loader_mem.dcp}}]
add_files -quiet {{/home/tyh/Desktop/project /project.srcs/mig_7series_0/ip/mig_7series_0/mig_7series_0.dcp}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/mig_7series_0/ip/mig_7series_0/mig_7series_0.dcp}}]
add_files -quiet {{/home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.dcp}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.dcp}}]
add_files -quiet {{/home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem.dcp}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem.dcp}}]
read_verilog /home/tyh/Documents/cache-design/code/status.vh
read_verilog -library xil_defaultlib -sv {
  /home/tyh/SYS_LAB/Pipeline-cpu/src/vga_view.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/vga_ctrl.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/vga_module.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/vga.v
}
read_verilog -library xil_defaultlib {
  /home/tyh/Documents/cache-design/code/memc.v
  /home/tyh/Documents/cache-design/code/memv.v
  /home/tyh/Documents/cache-design/code/cache_word_memc.v
  /home/tyh/Documents/cache-design/code/direct_mapped_cache.v
  /home/tyh/Documents/cache-design/code/victim_line_decide.v
  /home/tyh/Documents/cache-design/code/cache_control.v
  /home/tyh/Documents/cache-design/code/two_ways_cache.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/cache/DDRControlModule.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/spi_tr8.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/adder.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/alu_controller.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/count_leading_zero.v
  /home/tyh/Documents/cache-design/code/cache_top.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/load_b_w_e_gen.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/cache/ddr_control.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/interrupt_except_handle.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/FU.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/idex_reg.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/except_detect1.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/muldiv.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/exmem_reg.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/hex_to_seg.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/decoder.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/ALU.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/SHIFT.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/Ext_unit.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/pc.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/reg_w_gen.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/GPR.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/cp0.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/control_unit.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/is_delayslot.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/except_detect2.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/ifid_reg.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/memwb_reg.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/final_target.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/keyboard.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/store_b_w_e_gen.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/load_shifter.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/store_shifter.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/spi_flash.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/MUX.v
  /home/tyh/Documents/cache-design/code/cache_manage_unit.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/clock_control.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/breakpoint.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/cpu_top.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/seg_ctrl.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/cpu_interface.v
  /home/tyh/SYS_LAB/Pipeline-cpu/src/pipeline.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/tyh/Desktop/project /project.srcs/constrs_1/imports/constrain/top.xdc}}
set_property used_in_implementation false [get_files {{/home/tyh/Desktop/project /project.srcs/constrs_1/imports/constrain/top.xdc}}]


synth_design -top pipeline -part xc7a100tcsg324-1


write_checkpoint -force -noxdef pipeline.dcp

catch { report_utilization -file pipeline_utilization_synth.rpt -pb pipeline_utilization_synth.pb }
