# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.xci
# IP: The module: 'ddr_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.xci
# IP: The module: 'ddr_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tyh/Desktop/project /project.srcs/ddr_clock_gen/ip/ddr_clock_gen/ddr_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
