# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem.xci
# IP: The module: 'text_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'text_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem.xci
# IP: The module: 'text_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyh/Desktop/project /project.srcs/sources_1/ip/text_mem/text_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'text_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
